##
# libLinux Makefile
##

TARGET_BASE:=		Linux

# Uncomment to compile in debug mode.
#DEBUG:=			true

ROOT:=		../../..
JNI_LINUX_INCLUDES:=	-I$(ROOT)/linux
JNI_LINUX_LINK:= 	-lLCJNI -lX11

JAVAH_CLASSES:=	com.lightcrafts.platform.linux.LinuxKeyUtil

include		../jni-linux.mk

# vim:set noet sw=8 ts=8:
