/* Copyright (C) 2005-2011 Fabio Riccardi */

package com.lightcrafts.utils;

import lombok.Getter;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import java.util.ResourceBundle;

/** A container and accessor for static version data, either configured in
 * properties or added to resources at compile time.
 * <p>
 * The compile-time files are generated by the "generateGitProperties"
 * Gradle task, which writes the latest git hash and tag into git.properties.
 */
public final class Version {

    private static final Logger logger = LoggerFactory.getLogger(Version.class);

    /**
     * Gets the application's name.
     *
     * @return Returns said name.
     */
    public static String getApplicationName() {
        return m_properties.getString( "app-name" );
    }

    private static @Nullable URL getURLOrNull(String propertyKey) {
        try {
            return new URI(m_properties.getString(propertyKey)).toURL();
        }
        catch (MalformedURLException | URISyntaxException e) {
            return null;
        }
    }

    public static @Nullable URL getApplicationURL() {
        return getURLOrNull("app-URL");
    }

    public static @Nullable URL getHelpURL() {
        return getURLOrNull("Help-URL");
    }

    public static @Nullable URL getVideoLearningCenterURL() {
        return getURLOrNull("VideoLearningCenter-URL");
    }

    public static Map<String, URL> getVideoURLs() {
        Map<String, URL> map = new HashMap<>();
        // TODO put in final video URLs
        map.put("Introduction to Relight", getVideoLearningCenterURL());
        map.put("Advanced Relight", getVideoLearningCenterURL());
        map.put("Introduction to ZoneMapper", getVideoLearningCenterURL());
        map.put("Advanced ZoneMapper", getVideoLearningCenterURL());
        return map;
    }

    @NotNull
    public static String getVersionText() {
        return revisionNumber.isEmpty()
                ? "version " + versionName
                : "version " + versionName + " (" + revisionNumber + ')';
    }

    /**
     * This is where the actual labels for the tags are.
     */
    private static final ResourceBundle m_properties =
            ResourceBundle.getBundle( "com.lightcrafts.utils.resources.Version" );

    /**
     * Abbreviated (7 characters) git revision number that was current at the time
     * this class was compiled.
     */
    @Getter @NotNull
    private static final String revisionNumber;

    /**
     * User-presentable version String.
     */
    @Getter @NotNull
    private static final String versionName;

    static {
        final var props = new Properties();
        try (InputStream in = Version.class.getResourceAsStream("/git.properties")) {
            props.load(in);
        } catch (IOException | NullPointerException e) {
            logger.error("Failed to load git.properties", e);
        }
        versionName = props.getProperty("git.build.version", "unknown");
        revisionNumber = props.getProperty("git.commit.id.abbrev", "");
    }
}
/* vim:set et sw=4 ts=4: */
