TARGET_BASE:=		LCJNI

# Uncomment to compile in debug mode.
#DEBUG:=		true

ifeq ($(PLATFORM),MacOSX)
  JNI_MACOSX_SHAREDLIB:=	1
endif
JNI_WINDOWS_IMPLIB:=	1

ROOT:=			../../..
include			../jni.mk

# vim:set noet sw=8 ts=8:
