#!/bin/sh
#
# LightZone startscript
#
echo Starting LightZone version 4.1.0 beta6 ...
echo with options : ${@}

arch=`getconf LONG_BIT`
totalmem=`cat /proc/meminfo | grep MemTotal | sed -r 's/.* ([0-9]+) .*/\1/'`
if [ $totalmem -ge 1024000 ]; then
        maxmem=$(( $totalmem / 2 ))
        # on 32-bit architectures there is ~2GB limit for maximum Java heap size
        if [ $arch = "32" -a $totalmem -ge 4096000 ]; then
                maxmem=2048000
        fi
else
        maxmem=512000
fi

(cd "/opt/lightzone" && LD_PRELOAD="$lzmalibrary" LD_LIBRARY_PATH="/opt/lightzone" exec java -Xmx${maxmem}k -Djava.library.path="/opt/lightzone" -Dfile.encoding=UTF8 -classpath "/opt/lightzone/*" com.lightcrafts.platform.linux.LinuxLauncher ${@} )
