#!/bin/sh
#
# LightZone startscript
#
echo Starting LightZone version 3.9.0. ...
echo with options : ${@}

(cd "/opt/lightzone" && LD_LIBRARY_PATH="/opt/lightzone" exec java -Xmx256m -Djava.library.path="/opt/lightzone" -classpath "/opt/lightzone/*" com.lightcrafts.platform.linux.LinuxLauncher ${@} )
