HIGH_PERFORMANCE:=	1

TARGET_BASE:=		LCLENSFUN

JNI_EXTRA_CFLAGS:=	-std=c++14
JNI_EXTRA_PKGCFG:=	lensfun

JAVAH_CLASSES:=		com.lightcrafts.utils.Lensfun

ROOT:=			../../..
include			../jni.mk

# vim:set noet sw=8 ts=8:
