TARGET_BASE:=	LightZone-forkd

# Uncomment to compile in debug mode.
#DEBUG:=		true

EXEC_MACOSX_DEFINES:= -DUSE_FORKER
EXEC_LINUX_DEFINES:= -DUSE_FORKER

ROOT:=		../../..
include		$(ROOT)/lightcrafts/mk/executable.mk

# vim:set noet sw=8 ts=8:
