TARGET_BASE:=	LCFileUtil

# Uncomment to compile in debug mode.
#DEBUG:=		true

JNI_EXTRA_LINK:=	-lLCJNI

JAVAH_CLASSES:=	com.lightcrafts.utils.file.FileUtil

ROOT:=		../../..
include		../jni.mk

# vim:set noet sw=8 ts=8:
