lightcrafts/lib/jai-lightzone-*.jar usr/share/java/lightzone
lightcrafts/lib/laf-widget.jar usr/share/java/lightzone
lightcrafts/lib/substance-lite.jar usr/share/java/lightzone
lightcrafts/products/*.so usr/lib/lightzone
lightcrafts/products/LightZone-forkd usr/lib/lightzone
lightcrafts/products/dcraw_lz usr/lib/lightzone
lightcrafts/products/lightcrafts.jar usr/share/java/lightzone
linux/products/lightcrafts-linux.jar usr/share/java/lightzone
linux/products/lightzonehelp.jar usr/share/java/lightzone
linux/products/lightzone usr/bin
linux/products/lightzone.desktop usr/share/applications
linux/icons/hicolor/256x256/apps/* usr/share/icons/hicolor/256x256/apps
linux/icons/hicolor/128x128/apps/* usr/share/icons/hicolor/128x128/apps
linux/icons/hicolor/64x64/apps/* usr/share/icons/hicolor/64x64/apps
linux/icons/hicolor/48x48/apps/* usr/share/icons/hicolor/48x48/apps
linux/icons/hicolor/32x32/apps/* usr/share/icons/hicolor/32x32/apps
linux/icons/hicolor/16x16/apps/* usr/share/icons/hicolor/16x16/apps

