#!/bin/sh
chmod +x /usr/bin/lightzone
chmod +x /usr/share/java/lightzone/LightZone-forkd
chmod +x /usr/share/java/lightzone/dcraw_lz

if [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
