TARGET_BASE:=	LCArrays

# Uncomment to compile in debug mode.
#DEBUG:=		true

JNI_WINDOWS_LINK:=	-lLCJNI
JNI_LINUX_LINK:=	$(JNI_WINDOWS_LINK)
JNI_MACOSX_LINK:=	../jniutils/libLCJNI.a

JAVAH_CLASSES:=	com.lightcrafts.utils.LCArrays

ROOT:=		../../..
include		../jni.mk

# vim:set noet sw=8 ts=8:
