TARGET_BASE:=	LCArrays

# Uncomment to compile in debug mode.
#DEBUG:=		true

JNI_EXTRA_LINK:=	-lLCJNI

JAVAH_CLASSES:=	com.lightcrafts.utils.LCArrays

ROOT:=		../../..
include		../jni.mk

# vim:set noet sw=8 ts=8:
