TARGET_BASE:=	LCCache

# Uncomment to compile in debug mode.
#DEBUG:=		true

JNI_EXTRA_LINK:=	-lLCJNI

JAVAH_CLASSES:=	com.lightcrafts.utils.cache.NativeByteBufferAllocator \
		com.lightcrafts.utils.cache.NativeChunk

ROOT:=		../../..
include		../jni.mk

# vim:set noet sw=8 ts=8:
