##
# We need to specify this manually so that jniutils is built first.
##
SUBDIRS:=	jniutils \
		cache \
		dcraw \
		EDISON \
		jai \
		fast_jai \
		fast_bilateral \
		lensfun \
		jpeg \
		lcms \
		tiff

include	../mk/recurse.mk

# vim:set noet sw=8 ts=8:
